In [45]:
import pandas as pd
import statsmodels.api as sm

tommy_johns = pd.read_csv('Tommy_John_Surgery_List.csv', skiprows = 1, usecols = ["Player", "TJ Surgery Date"])
pitch_velocity = pd.read_csv('savant_data_pitch_velocity.csv', usecols = ["player_name", "velocity", "total_pitches", "spin_rate"])
tommy_johns = tommy_johns.dropna(how = 'all')

tommy_johns['Player'] = tommy_johns['Player'].apply(lambda x: ', '.join(x.split()[::-1]))

result = pd.merge(pitch_velocity, tommy_johns, how = 'left', left_on = ['player_name'], right_on = ['Player'])

#result['TJ'] = result['TJ Surgery Date'].notna().astype(int)
#result = result[['player_name', 'velocity', 'TJ', 'total_pitches', 'spin_rate']]
#result = result[result['total_pitches']>1000]

#model = sm.Logit(result['TJ'], result[['velocity', 'total_pitches']]).fit()
#model.summary()

result = result.dropna(subset = ['TJ Surgery Date'])
result

,player_name,total_pitches,spin_rate,velocity,Player,TJ Surgery Date
1,"Verlander, Justin",48086,2529.0,94.8,"Verlander, Justin",9/30/2020
2,"Lynn, Lance",33084,2406.0,92.3,"Lynn, Lance",11/10/2015
7,"Wainwright, Adam",37059,2256.0,88.7,"Wainwright, Adam",2/28/2011
9,"Cueto, Johnny",35931,2223.0,92.1,"Cueto, Johnny",8/2/2018
14,"Lackey, John",26324,2177.0,90.0,"Lackey, John",11/1/2011
...,...,...,...,...,...,...
2991,"Calvo, Blair",11,1975.0,93.7,"Calvo, Blair",1/1/2017
3007,"Beeter, Clayton",3,2303.0,95.8,"Beeter, Clayton",12/1/2017
3008,"Snyder, Kyle",27,NaN,89.8,"Snyder, Kyle",9/7/2000
3011,"Gentry, Craig",20,NaN,87.6,"Gentry, Craig",1/1/2005
3018,"Kelly, Don",5,NaN,86.8,"Kelly, Don",7/14/2015

In [63]:
import pandas as pd
import matplotlib.pyplot as plt

tommy_johns = pd.read_csv('Tommy_John_Surgery_List.csv', skiprows = 1, usecols = ["Year"])
tommy_johns = tommy_johns.dropna(how = 'all')

counts = tommy_johns['Year'].value_counts(sort = False).reset_index()

#fig, ax = plt.subplots()
#counts['count'].plot(ax=ax, color="black")